using System;
using Microsoft.Xna.Framework;

namespace ClassicUO.Renderer.Effects;

/// <summary>
/// Which packed channel of the noise texture a noise field reads. The four are generated by
/// different algorithms, not merely different seeds, so the choice changes the character of the
/// result far more than any numeric parameter does.
/// </summary>
public enum NoiseChannel
{
    /// <summary>Perlin fBm, base frequency 4. Soft billowy masses. The general-purpose choice.</summary>
    Red,

    /// <summary>Perlin fBm, base frequency 8. Same character as <see cref="Red"/>, finer.</summary>
    Green,

    /// <summary>Ridged fBm. Thin bright filaments. Cracks and lightning, never fluid or gas.</summary>
    Blue,

    /// <summary>
    /// Worley <c>F2 - F1</c>. Cell edges - a lattice of polygons with outlined borders. Only
    /// ever right for shattering and crazing; on anything organic it reads as a microscope slide.
    /// </summary>
    Alpha
}

public static class NoiseChannelExtensions
{
    public static Vector4 ToSelector(this NoiseChannel channel)
    {
        switch (channel)
        {
            case NoiseChannel.Red: return new Vector4(1, 0, 0, 0);
            case NoiseChannel.Green: return new Vector4(0, 1, 0, 0);
            case NoiseChannel.Blue: return new Vector4(0, 0, 1, 0);
            default: return new Vector4(0, 0, 0, 1);
        }
    }
}

/// <summary>
/// Breaks up the shape boundary with its own noise field. The mask is a function of distance to
/// the nearest screen edge alone, so with no jitter the effect terminates along a perfectly
/// straight iso-line - every column of a border trim ends at the same depth, which reads as a
/// rectangle. Anything organic wants <see cref="ReachAmount"/> well above 0.
/// </summary>
public struct OverlayJitter
{
    /// <summary>
    /// How far the boundary can move, as a fraction of the shape distance. Note this only ever
    /// extends the effect inward on the deep half of the field, so raising it also raises the
    /// average reach - compensate with <see cref="OverlayShape.Reach"/>.
    /// </summary>
    public float ReachAmount;

    /// <summary>
    /// How much the same field stretches and compresses <see cref="OverlayShape.Feather"/>, as a
    /// fraction of it. Without this the effect reaches a varying distance behind a gradient of
    /// fixed length; with it, the gradient is longer where it reaches further, so a deep run
    /// tapers away and a shallow one ends bluntly.
    /// </summary>
    public float FeatherAmount;

    /// <summary>
    /// Frequency of the displacement, and the parameter most often set wrong. It must be coarser
    /// than <see cref="OverlayNoise.BaseScale"/> or the boundary merely buzzes at the detail
    /// frequency instead of making some columns reach deeper and hold it - but the X component
    /// still has to complete several cycles across the screen, or each edge gets one gentle
    /// bulge and stays visibly rectangular.
    /// </summary>
    public Vector2 Scale;

    /// <summary>
    /// Texture-space velocity of the displacement field. Usually matched to the layer's own
    /// scroll speed so the ragged edge travels with the effect rather than crawling across it.
    /// </summary>
    public Vector2 Scroll;

    public NoiseChannel Channel;
}

/// <summary>
/// Where on screen the effect lives: vignette/border shape, how far it extends, and how its
/// boundary breaks up.
/// </summary>
public struct OverlayShape
{
    /// <summary>Centre of the radial falloff in screen uv. (0.5, 0.5) is the middle.</summary>
    public Vector2 Center;

    /// <summary>
    /// Rate <see cref="Center"/> drifts at, in Hz per axis. Different X and Y values give a
    /// Lissajous wander instead of a back-and-forth pendulum. Zero on either axis holds that axis
    /// still, so a preset with no wobble simply leaves both at zero rather than needing a
    /// separate on/off switch.
    /// </summary>
    public Vector2 WobbleFreq;

    /// <summary>Peak drift of <see cref="Center"/>, in screen uv. Kept small - this is meant to
    /// unsteady the effect's pivot, not send it touring the screen.</summary>
    public float WobbleAmp;

    /// <summary>
    /// How far in from the screen edge the effect extends, roughly as a fraction of the distance
    /// to the centre. Larger is thicker. Interacts with <see cref="EdgeBlend"/>: on a widescreen
    /// display a radial shape reaches much further at the corners and the left/right edges than
    /// it does at the top and bottom, so the same value covers noticeably less screen.
    /// </summary>
    public float Reach;

    /// <summary>
    /// Width of the fade behind the boundary. Wide values thin the effect into a haze; narrow
    /// values give it a defined surface and a more abrupt end.
    /// </summary>
    public float Feather;

    /// <summary>
    /// 0 = radial vignette, 1 = border trim.
    /// <para>
    /// Beware of using intermediate values to weight a border trim toward its corners. The
    /// radial term is normalised to screen width, so on a widescreen display the distance to the
    /// top edge is far shorter than to the left edge and any radial blend visibly favours the
    /// left and right sides. Use <see cref="CornerBias"/> instead, which is measured per axis
    /// and has no aspect bias.
    /// </para>
    /// </summary>
    public float EdgeBlend;

    /// <summary>
    /// Corner weighting of the border trim, ignored when <see cref="EdgeBlend"/> is 0. At 0 the
    /// trim is a rectangle: uniform thickness all the way round with sharp corners, which reads
    /// as a picture frame. Raising it lets both axes contribute near a corner so the trim
    /// thickens and rounds there, without favouring any one edge.
    /// </summary>
    public float CornerBias;

    public OverlayJitter Jitter;

    /// <summary>Unit vector biasing the effect toward one side or corner.</summary>
    public Vector2 FocusDir;

    /// <summary>Higher values tighten the directional lobe.</summary>
    public float FocusPower;

    /// <summary>0 = uniform all the way round, 1 = fully biased toward <see cref="FocusDir"/>.</summary>
    public float FocusAmount;
}

/// <summary>
/// How the effect moves and what texture it has: two scrolling samples of the tiling noise
/// texture, the second domain-warped by the first.
/// </summary>
public struct OverlayNoise
{
    /// <summary>
    /// Frequency of the primary field. The X:Y ratio is the anisotropy, and it is the main
    /// control over whether features read as blobs (near 1:1) or as streaks (4:1 and beyond).
    /// </summary>
    public Vector2 BaseScale;

    /// <summary>
    /// Texture-space velocity. On-screen speed is <c>Scroll / Scale</c>, not <c>Scroll</c>, so
    /// two layers with matching scroll values but different scales visibly slide against each
    /// other. Prefer to derive scroll from a target screen speed.
    /// </summary>
    public Vector2 BaseScroll;

    public NoiseChannel BaseChannel;

    /// <summary>Frequency of the secondary field, whose lookup is warped by the primary.</summary>
    public Vector2 DetailScale;

    public Vector2 DetailScroll;
    public NoiseChannel DetailChannel;

    /// <summary>
    /// Static texture-space shift applied to both fields' lookups. Unlike <see cref="BaseScroll"/>
    /// and <see cref="DetailScroll"/> this never varies with time - its only job is to desync one
    /// layer from another that otherwise shares its scale and scroll, so two such layers do not
    /// read as the same texture traced twice.
    /// </summary>
    public Vector2 Offset;

    /// <summary>
    /// How far the primary field displaces the secondary field's lookup. The single strongest
    /// control over character: high values churn and billow (gas), near-zero values let the
    /// pattern translate coherently (fluid, or anything solid).
    /// </summary>
    public float WarpStrength;

    /// <summary>
    /// Blends in <c>(1 - |2n - 1|)²</c>, which outlines the field's median. Good for cracks and
    /// filaments. Counterintuitive in two ways: the transform peaks at the field's *most common*
    /// value, so raising it makes a layer cover more of the screen rather than less, and what it
    /// draws are outlines, so on a soft field it produces bordered cells.
    /// </summary>
    public float RidgeAmount;

    /// <summary>
    /// Cut-off applied to the field. Higher keeps less, so the layer gets sparser and its
    /// features narrower.
    /// </summary>
    public float Threshold;

    /// <summary>
    /// Width of the fade either side of <see cref="Threshold"/>. Small values give hard-edged
    /// surfaces; large values give soft-edged clouds.
    /// </summary>
    public float Softness;

    /// <summary>
    /// Solid fill blended under the noise: 1 is flat colour with no texture at all (tunnel
    /// vision), 0 is fully noise-driven. Anything above 0 makes the shape mask itself visible as
    /// a geometric form, so a layer that should read as discrete streaks or wisps needs this at
    /// exactly 0 - it is not a way to add weight, only a way to fill the shape in.
    /// </summary>
    public float FlatFloor;
}

/// <summary>
/// Colour and time-varying strength of the effect.
/// </summary>
public struct OverlayAppearance
{
    public Color Tint;

    /// <summary>Peak alpha where the field is fully present.</summary>
    public float Opacity;

    /// <summary>
    /// Overall strength, multiplied by the fade envelope and the global setting before upload.
    /// Presets should leave this as the caller's dial and express their own balance through
    /// <see cref="Opacity"/>.
    /// </summary>
    public float Intensity;

    /// <summary>
    /// Breathing rate in Hz. Hard-capped at <see cref="OverlayParams.MaxPulseFreqHz"/> for
    /// photosensitivity reasons.
    /// </summary>
    public float PulseFreq;

    /// <summary>Depth of that breathing, as a fraction of <see cref="Opacity"/>.</summary>
    public float PulseAmp;
}

public struct OverlayParams
{
    // Flashing above ~3 Hz is a photosensitive-epilepsy hazard. Hard ceiling, not configurable
    // upward by any preset or setting.
    public const float MaxPulseFreqHz = 3.0f;

    /// <summary>Tap count used where a stored one is not a defined
    /// <see cref="OverlaySampleTaps"/>, which only a hand-edited profile can produce.</summary>
    private const OverlaySampleTaps DEFAULT_SAMPLE_TAPS = OverlaySampleTaps.Twelve;

    /// <summary>Blur radius ceiling as a fraction of screen width. Beyond this the frame is
    /// unreadable rather than merely blurred.</summary>
    public const float MaxSampleRadius = 0.06f;

    /// <summary>Chromatic separation ceiling. Past this the three channels stop reading as one
    /// image.</summary>
    public const float MaxSampleAberration = 0.05f;

    /// <summary>Centre-drift rate ceiling, in Hz. A motion-sickness bound rather than the
    /// flash-hazard one <see cref="MaxPulseFreqHz"/> guards against - past this the pivot swings
    /// fast enough to read as camera shake rather than an unsteady wander.</summary>
    public const float MaxWobbleFreqHz = 1.0f;

    /// <summary>Centre-drift range ceiling, in screen uv. Past this the effect's own focal point
    /// visibly tours the screen instead of just feeling unsteady.</summary>
    public const float MaxWobbleAmp = 0.15f;

    private const float MIN_FEATHER = 0.01f;

    // A zero jitter scale collapses the displacement lookup onto a single texel, which reads as
    // a uniform offset rather than a varying boundary. Presets that leave the field unset get
    // this instead.
    private static readonly Vector2 _defaultJitterScale = new(2f, 2f);

    public OverlayShape Shape;
    public OverlayNoise Noise;
    public OverlayAppearance Appearance;
    public OverlaySampling Sampling;

    public static OverlayParams Default => new OverlayParams
    {
        Shape = new OverlayShape
        {
            Center = new Vector2(0.5f, 0.5f),
            WobbleFreq = Vector2.Zero,
            WobbleAmp = 0f,
            Reach = 0.6f,
            Feather = 0.3f,
            EdgeBlend = 0f,
            CornerBias = 0f,
            Jitter = new OverlayJitter
            {
                ReachAmount = 0f,
                FeatherAmount = 0f,
                Scale = _defaultJitterScale,
                Scroll = Vector2.Zero,
                Channel = NoiseChannel.Red
            },
            FocusDir = new Vector2(0f, -1f),
            FocusPower = 1f,
            FocusAmount = 0f
        },
        Noise = new OverlayNoise
        {
            BaseScale = new Vector2(3f, 3f),
            BaseScroll = Vector2.Zero,
            BaseChannel = NoiseChannel.Red,
            DetailScale = new Vector2(6f, 6f),
            DetailScroll = Vector2.Zero,
            DetailChannel = NoiseChannel.Green,
            Offset = Vector2.Zero,
            WarpStrength = 0.2f,
            RidgeAmount = 0f,
            Threshold = 0.5f,
            Softness = 0.2f,
            FlatFloor = 0f
        },
        Appearance = new OverlayAppearance
        {
            Tint = Color.White,
            Opacity = 0.5f,
            Intensity = 1f,
            PulseFreq = 0f,
            PulseAmp = 0f
        },
        Sampling = new OverlaySampling
        {
            Mode = OverlaySampleMode.None,
            Radius = 0.012f,
            Taps = DEFAULT_SAMPLE_TAPS,
            Zoom = 0.15f,
            Aberration = 0.01f
        }
    };

    /// <summary>
    /// Enforces the safety and sanity bounds every preset and every runtime override must obey.
    /// Mandatory before upload - never skip this to let a caller "just try a higher value".
    /// </summary>
    public void Clamp()
    {
        Appearance.PulseFreq = MathHelper.Clamp(Appearance.PulseFreq, 0f, MaxPulseFreqHz);
        Appearance.PulseAmp = MathHelper.Clamp(Appearance.PulseAmp, 0f, 1f);
        Appearance.Opacity = MathHelper.Clamp(Appearance.Opacity, 0f, 1f);
        Appearance.Intensity = MathHelper.Clamp(Appearance.Intensity, 0f, 1f);

        Noise.FlatFloor = MathHelper.Clamp(Noise.FlatFloor, 0f, 1f);
        Noise.RidgeAmount = MathHelper.Clamp(Noise.RidgeAmount, 0f, 1f);

        Shape.WobbleFreq.X = MathHelper.Clamp(Shape.WobbleFreq.X, 0f, MaxWobbleFreqHz);
        Shape.WobbleFreq.Y = MathHelper.Clamp(Shape.WobbleFreq.Y, 0f, MaxWobbleFreqHz);
        Shape.WobbleAmp = MathHelper.Clamp(Shape.WobbleAmp, 0f, MaxWobbleAmp);

        Shape.Reach = MathHelper.Clamp(Shape.Reach, 0f, 1f);
        Shape.CornerBias = MathHelper.Clamp(Shape.CornerBias, 0f, 1f);
        Shape.FocusAmount = MathHelper.Clamp(Shape.FocusAmount, 0f, 1f);
        Shape.Feather = MathHelper.Max(Shape.Feather, MIN_FEATHER);

        // Beyond 1 the displacement exceeds the range of the shape distance itself and the
        // overlay stops having a recognisable shape at all.
        Shape.Jitter.ReachAmount = MathHelper.Clamp(Shape.Jitter.ReachAmount, 0f, 1f);

        // At 1 the falloff varies between zero and twice Feather. The shader floors the low end
        // so it can never become an aliased hard edge, but past 1 it would invert.
        Shape.Jitter.FeatherAmount = MathHelper.Clamp(Shape.Jitter.FeatherAmount, 0f, 1f);

        if (Shape.Jitter.Scale == Vector2.Zero)
            Shape.Jitter.Scale = _defaultJitterScale;

        Sampling.Radius = MathHelper.Clamp(Sampling.Radius, 0f, MaxSampleRadius);
        Sampling.Zoom = MathHelper.Clamp(Sampling.Zoom, 0f, 1f);
        Sampling.Aberration = MathHelper.Clamp(Sampling.Aberration, 0f, MaxSampleAberration);

        // Only the defined counts have a compiled technique, and a profile is hand-editable
        // JSON: an out-of-range value would otherwise reach the technique lookup.
        if (!Enum.IsDefined(Sampling.Taps))
            Sampling.Taps = DEFAULT_SAMPLE_TAPS;
    }
}
